version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running pre-build commands...
  build:
    commands:
      - echo Building the code...
      - python setup.py install
  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - '**/*'
  discard-paths: yes
