version: 0.2


phases:
  install:
    commands:
      - export NGINX_IMAGE_REPOSITORY=rapidfort/nginx
      - export NGINX_IMAGE_TAG=latest
      - export RF_ACCESS_TOKEN=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

  build:
    commands:
      - echo "Listing files in the repository"
      - ls -R
      - echo "Navigating to the Docker Compose directory"
      - cd community_images/nginx/bitnami
      - echo "Building Docker image using Docker Compose"
      - docker-compose build
      - docker image ls
