version: 0.2

phases:
  install:
    commands:
      - echo "Installing Docker..."
      # Install dependencies for Docker
      - apt-get update -y || yum update -y
      # Install Docker for Ubuntu/Debian environments
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      # Start Docker service
      - dockerd > /dev/null 2>&1 &
      # Confirm Docker is running
      - docker --version
  pre_build:
    commands:
      - echo Running pre-build commands...
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 550843840101.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - echo Building the Docker image...
      - docker-compose -f community_images/nginx/bitnami/docker-compose.yml build || cat /var/log/docker.log
  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - '**/*'
  discard-paths: yes
