version: 0.2


phases:
  install:
    commands:

       # Below variables are required to spinup nginx image
      - export NGINX_IMAGE_REPOSITORY=rapidfort/nginx
      - export NGINX_IMAGE_TAG=latest
      - export RF_ACCESS_TOKEN=Your_Github_Personal_AccessToken


  build:
    commands:

      - echo "Pulling the rapidfort/nginx image from Docker Hub"
      - docker image ls
      - cd community_images/nginx/bitnami
      - ls -ll
      - echo "Running docker-compose up command to create nginx image"
      - docker-compose up -d
      - docker ps -a

  post_build:
    commands:

      - echo "Find nginx-1 container  and Run coverage script in the container"
      - CONTAINER_ID=$(docker ps -qf "name=bitnami-nginx-1")
      - echo "Copying the coverage script to the container"
      - docker cp coverage_script.sh $CONTAINER_ID:/coverage_script.sh
      
      - echo "Running the coverage script inside the container"
      - |
        if ! docker exec $CONTAINER_ID bash /coverage_script.sh > /tmp/coverage_output.log 2>&1; then
          echo "Coverage script failed, sending SNS notification";
          aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
                          --subject "Build Failed: NGINX Coverage Script" \
                          --message "The coverage script failed to execute. Check the logs for details.\n\n$(cat /tmp/coverage_output.log)";
          exit 1;
      - docker ps -a
        fi
    