version: 0.2

phases:
  install:
    commands:
      - echo "Installing Docker with root permissions..."
      # Update system and install curl if necessary
      - sudo apt-get update -y || sudo yum update -y
      - sudo apt-get install -y curl || sudo yum install -y curl
      # Download Docker installation script
      - sudo curl -fsSL https://get.docker.com -o get-docker.sh
      # Give executable permissions to the script
      - sudo chmod +x get-docker.sh
      # Execute the Docker installation script with root permissions
      - sudo ./get-docker.sh
      # Start Docker daemon in the background with root permissions
      - sudo dockerd > /dev/null 2>&1 &
      # Verify Docker installation
      - sudo docker --version
  pre_build:
    commands:
      - echo Running pre-build commands...
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 550843840101.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - echo Building the Docker image...
      - docker-compose -f community_images/nginx/bitnami/docker-compose.yml build || cat /var/log/docker.log
  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - '**/*'
  discard-paths: yes
