version: 0.2

variables:
  NGINX_IMAGE_REPOSITORY: 'rapidfort/nginx'
  NGINX_IMAGE_TAG: 'latest'
  AWS_ECR_REPOSITORY: '550843840101.dkr.ecr.us-east-1.amazonaws.com/rapidfort/nginx'

phases:
  install:
    commands:
      - export NGINX_IMAGE_REPOSITORY=rapidfort/nginx
      - export NGINX_IMAGE_TAG=latest
      - export  AWS_ECR_REPOSITORY=550843840101.dkr.ecr.us-east-1.amazonaws.com/rapidfort/nginx

  pre_build:
    commands:
      - docker image ls
      - docker-compose -f community_images/nginx/bitnami/docker-compose.yml build
      - docker image ls

      - echo Running pre-build commands...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 550843840101.dkr.ecr.us-east-1.amazonaws.com
      - docker push rapidfort/nginx:latest
      
  build:
    commands: []

  post_build:
    commands: []

artifacts:
  files:
    - '**/*'
  discard-paths: yes
