version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "/rapidfort/DOCKER_USERNAME"
    DOCKER_PASSWORD: "/rapidfort/DOCKER_PASSWORD"
    APACHE_IMAGE_REPOSITORY: "/rapidfort/NGINX_IMAGE_REPOSITORY"
    APACHE_IMAGE_TAG: "/rapidfort/NGINX_IMAGE_TAG"
    RF_ACCESS_TOKEN: "/rapidfort/RF_ACCESS_TOKEN"

phases:
  install:
    commands:
      - echo "Testing if environment variables are set"
      - echo "Logging in to Docker Hub"
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  build:
    commands:
      - echo "Pulling the rapidfort/apache image from Docker Hub"
      - cd community_images/apache/bitnami
      - echo "Running docker-compose up"
      - docker-compose up -d
      - docker ps -a

  post_build:
    commands:
      - echo "Running coverage script in the container"
      - CONTAINER_ID=$(docker ps -qf "name=bitnami-apache-1")
      - echo "Copying the coverage script to the container"
      - docker cp coverage_script.sh $CONTAINER_ID:/coverage_script.sh
      - echo "Running the coverage script inside the container"
      - |
        if ! docker exec $CONTAINER_ID bash /coverage_script.sh > /tmp/coverage_output.log 2>&1; then
          echo "apache Coverage script failed, Please check the logs, sending SNS notification";
          aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
                          --subject "Build Failed: apache Coverage Script" \
                          --message "The coverage script failed to execute. Check the logs for details.\n\n$(cat /tmp/coverage_output.log)";
          exit 1;
        else
          echo "apache Coverage script succeeded, Please check the logs, sending success notification with logs";
          aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
                          --subject "Build Succeeded: apache Coverage Script" \
                          --message "The coverage script executed successfully. Here are the logs:\n\n$(cat /tmp/coverage_output.log)";
        fi
