version: 0.2


phases:
  install:
    commands:
      - echo "Logging in to Docker Hub"
      - export NGINX_IMAGE_REPOSITORY=rapidfort/nginx
      - export NGINX_IMAGE_TAG=latest
      - export RF_ACCESS_TOKEN=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

  build:
    commands:

      - echo "Pulling the rapidfort/nginx image from Docker Hub"
      - docker pull rapidfort/nginx
      - echo "Listing Docker images"
      - docker image ls

  post_build:
    commands:
    
      # - echo "Running the Docker container"
      # - docker run -d -p 80:80 --name my_nginx_container rapidfort/nginx
      # - echo "Copying the coverage script to the container"
      # - docker cp community_images/nginx/bitnami/coverage_script.sh my_nginx_container:/coverage_script.sh
      # - echo "Making the script executable"
      # # - docker exec my_nginx_container chmod +x /coverage_script.sh
      # - echo "Running the coverage script inside the container"
      # - docker exec my_nginx_container bash -c "chmod +x /coverage_script.sh && /coverage_script.sh"

      - echo "Running the Docker container"
      - CONTAINER_ID=$(docker run -d -p 80:80 rapidfort/nginx)
      # - echo "Docker container started with ID: $CONTAINER_ID"
      - echo "Copying the coverage script to the container"
      - docker cp community_images/nginx/bitnami/coverage_script.sh $CONTAINER_ID:/coverage_script.sh
      - echo "Running the script inside the container"
      - docker exec $CONTAINER_ID bash -c "chmod +x /coverage_script.sh && /coverage_script.sh"
