version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
      - apt-get install -y docker-compose

  pre_build:
    commands:
      - echo "Pre-build phase... (no ECR login required)"

  build:
    commands:
      - echo "Building Docker image with Docker Compose..."
      - docker-compose -f nginx/bitnami/docker-compose.yml build

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
