version: 0.2

variables:
  NGINX_IMAGE_REPOSITORY: 'rapidfort/nginx'
  NGINX_IMAGE_TAG: 'latest'
  AWS_ECR_REPOSITORY: '550843840101.dkr.ecr.us-east-1.amazonaws.com/rapidfort/nginx'

phases:
  install:
    commands:     
    - echo Building the Docker image...
    - docker-compose -f community_images/nginx/bitnami/docker-compose.yml build

  pre_build:
    commands:


  build:
    commands: []

  post_build:
    commands: []

artifacts:
  files:
    - '**/*'
  discard-paths: yes

