version: 0.2

variables:
  NGINX_IMAGE_REPOSITORY: 'rapidfort/nginx'
  NGINX_IMAGE_TAG: 'latest'
  AWS_ECR_REPOSITORY: '550843840101.dkr.ecr.us-east-1.amazonaws.com/rapidfort/nginx'

phases:
  install:
    commands:
      - echo "Cloning the repository..."
      - git clone https://github.com/Arvindssurendra/rapidfort-test.git
      - cd rapidfort-test
      - echo "Listing files in the cloned repository..."
      - ls -al

  pre_build:
    commands:


  build:
    commands: []

  post_build:
    commands: []

artifacts:
  files:
    - '**/*'
  discard-paths: yes

