version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y docker-compose
  pre_build:
    commands:
      - echo Running pre-build commands...
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 550843840101.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - echo Building the Docker image...
      - docker-compose build
  post_build:
    commands:
      - echo Build complete

artifacts:
  files:
    - '**/*'
  discard-paths: yes
